### ISSUE TITLE
AUROC not good as in article

### ISSUE THREAD

**Issue by xulaupuz** [Vanixxz/MEDAF#3]
Hello, I run the code with only datasets path changed. I run with 2 datasets for now, for svhn I got only about 0.75 auroc, and for tinyimagenet, I got around 0.55, a bit better than purely random choice. 
I tried changing seeds, using another optimizer intergrated, configging learning rate, etc. And get almost same result said above.
Any suggestions for me? Thanks.

**Comment by Vanixxz** [comment]
Thank you very much for your reminder. We apologize for uploading the incorrect version of the test code, which has been corrected. The updated code can now reproduce results as described in the paper.
